### ISSUE TITLE
Error when creating single node job clusters

### ISSUE THREAD

**Issue by nsenno-dbr** [databricks/databricks-sdk-py#103]
When creating a single node job cluster, an error is thrown if the num_workers is set to 0. However, this is the same setting used when inspecting the JSON structure of a single node job cluster. 

Error message: 
`databricks.sdk.core.DatabricksError: Cluster validation error: Missing required field: settings.cluster_spec.new_cluster.size`

Cluster configuraiton: 

> {
            "job_cluster_key": "ascend_ingest",
            "new_cluster": {
                "spark_version": "12.2.x-scala2.12",
                "spark_conf": {
                    "spark.databricks.delta.preview.enabled": "true",
                    "spark.master": "local[*, 4]",
                    "spark.databricks.cluster.profile": "singleNode",
                },
                "azure_attributes": {
                    "first_on_demand": 1,
                    "availability": "ON_DEMAND_AZURE",
                    "spot_bid_max_price": -1,
                },
                "node_type_id": "Standard_DS3_v2",
                "custom_tags": {"ResourceClass": "SingleNode"},
                "spark_env_vars": {"PYSPARK_PYTHON": "/databricks/python3/bin/python3"},
                "enable_elastic_disk": True,
                "data_security_mode": "SINGLE_USER",
                "runtime_engine": "STANDARD",

                ## Seems theres a bug that won't allow for single node clusters
                "num_workers": 0,
            },
        }

Note that changing num_workers to 1 resolves the issue.

**Comment by nfx** [comment]
Insufficient details. We need to see the code calling the SDK. You’ve provided just a json. Currently we don’t expose any APIs that work directly with json

**Comment by nsenno-dbr** [comment]
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.jobs import (
    JobTaskSettings
)

import databricks.sdk.service.jobs as j

w = WorkspaceClient()

job_cluster_dicts = [
    {
        "job_cluster_key": "ascend_ingest",
        "new_cluster": {
            "spark_version": "12.2.x-scala2.12",
            "spark_conf": {
                "spark.databricks.delta.preview.enabled": "true",
            },
            "node_type_id": "Standard_DS3_v2",
            "custom_tags": {"ResourceClass": "SingleNode"},
            "data_security_mode": "SINGLE_USER",
            "runtime_engine": "STANDARD",

            ## Seems theres a bug that won't allow for single node clusters
            "num_workers": 0,
        },
    }
]

notebook_task = {
        "notebook_path": "/Repos/nsenno@elevate.com/EDA_DATABRICKS/Account/ascend/IngestionTemplate",
        "source": "WORKSPACE",
        "base_parameters": {
            "base1": "my_base_1", 
        }
    }

job_task_setting = {
    "task_key": "my_task", 
    "job_cluster_key": "ascend_ingest", 
    "notebook_task": notebook_task, 
}

job_task_setting = JobTaskSettings.from_dict(job_task_setting)

job_clusters = map(j.JobCluster.from_dict, job_cluster_dicts)

response = w.jobs.create(
    name="nick's test job",
    job_clusters=job_clusters,
    tasks=[job_task_setting],
)

**Comment by nsenno-dbr** [comment]
@nfx this is the full code require to reproduce the issue. Note that if we change `num_workers` to some number greater than zero the job is successfully created. However, this configuration is successful if created using the UI.

**Comment by nfx** [comment]
@nsenno-dbr you're not using dataclasses directly - https://github.com/databricks/databricks-sdk-py/blob/main/examples/jobs/create_jobs_api_full_integration.py, please reproduce it with the supported syntax
