### ISSUE TITLE
[BUG] Always return `None` from `model_registry.get_model()`

### ISSUE THREAD

**Issue by ddxgz** [databricks/databricks-sdk-py#109]
When calling API `WorkspaceClient.model_registry.get_model()`, it always returns `GetModelResponse(registered_model=None)`. 

However, the returned value is correct when I call the Web API directly with requests by passing the param.
```python
url = f"{host}/api/2.0/mlflow/databricks/registered-models/get"
resp = requests.get(url, headers=headers, params={"name": "model_name"})
```

Could you please take a look?

**Comment by nfx** [comment]
will be fixed the next version
