### ISSUE TITLE
Workspace Conf fails to get status

### ISSUE THREAD

**Issue by jaydm26** [databricks/databricks-sdk-py#128]
Hello,

When using the workspace_conf.get_status() in the WorkspaceClient, the method does not work and returns an `AttributeError: type object 'dict' has no attribute 'from_dict'`. I believe WorkspaceConf is just a dictionary and thus, it is raising an Attribute Error. Could you please verify and confirm if this is correct.

e.g. `workspace_client.workspace_conf.get_status(keys="enableTokensConfig")` does not work

Thank you.

**Comment by jaydm26** [comment]
Related to `get_status`, `set_status` returns `Bad Request`. e.g. to enable EBS SSD GP3, I used `workspace_client .workspace_conf.set_status(request={"enableGP3": True})`.

If this is not the right place for it, I apologize and will open a new issue.

Thank you.

**Comment by dbbnicole** [comment]
Running into the same issue here as we use SDK to develop a customer-facing product enablement notebook which sets and gets workspace confs. cc @bchiang2
