### ISSUE TITLE
Add examples for `grants` and other submodules

### ISSUE THREAD

**Issue by MigQ2** [databricks/databricks-sdk-py#132]
I see there are methods in `w.grants` but they're not documented in the `examples` path of the repo.

Also would be nice to add a `README.md` in the `examples` folder (or add it to the root README) stating that the structure of the SDK is the same as the URLs of the [REST API explorer](https://docs.databricks.com/api-explorer/). That would make it easier to know and navigate the complete functionality of the SDK

**Comment by nfx** [comment]
added more examples
