### ISSUE TITLE
[BUG] in jobs.py: TypeError: Object of type AccessControlRequest is not JSON serializable

### ISSUE THREAD

**Issue by SRSonix** [databricks/databricks-sdk-py#134]
In https://github.com/databricks/databricks-sdk-py/blob/1e3612d3e49a86381f333c54d64abf97c1aa92bc/databricks/sdk/service/jobs.py#L236 
the AccessControlRequest objects are put in the dict without modifying. This leads to 

> TypeError: Object of type AccessControlRequest is not JSON serializable

when calling JobsAPI.create

instead the line should be 

`if self.access_control_list: body['access_control_list'] = [v.as_dict() for v in self.access_control_list]`

**Comment by nfx** [comment]
this is the same code generator template bug, in fact - https://github.com/databricks/databricks-sdk-py/issues/135
