### ISSUE TITLE
[BUG] in jobs.py: TypeError: Object of type Library is not JSON serializable 

### ISSUE THREAD

**Issue by SRSonix** [databricks/databricks-sdk-py#135]
In https://github.com/databricks/databricks-sdk-py/blob/1e3612d3e49a86381f333c54d64abf97c1aa92bc/databricks/sdk/service/jobs.py#L703
the Library objects are put in the dict without modifying. This leads to 

> TypeError: Object of type Library is not JSON serializable

when calling JobsAPI.create with a Libray object set in a JobTask

instead the line should be 

`if self.libraries: body['libraries'] = [v.as_dict() for v in self.libraries]`

**Comment by nfx** [comment]
@SRSonix could you help and provide the small code sample to reproduce this? we'll release a fix shortly after.
