### ISSUE TITLE
`databricks.sdk.service.compute.BaseClusterInfo` is missing `docker_image` field

### ISSUE THREAD

**Issue by judahrand** [databricks/databricks-sdk-py#137]
This issue makes it impossible to use a custom container for a Cluster as documented here: https://docs.databricks.com/clusters/custom-containers.html

**Comment by nfx** [comment]
@judahrand which method do you experience this?

**Comment by judahrand** [comment]
```python
from databricks.sdk.service import jobs
from databricks.sdk.service import compute

jobs.JobCluster(
    job_cluster_key='job_key',
    new_cluster=jobs.BaseClusterInfo(
        docker_image=compute.DockerImage(
            url='example:latest',
            basic_auth=compute.DockerBasicAuth(
                username='username',
                password='password',
            ),
        ),
    ),
)
```

I need to be able to define a `docker_image` on a JobCluster.

**Comment by judahrand** [comment]
This issue makes this SDK unusable for us currently. We're having to use https://github.com/judahrand/databricks-jobs instead.

**Comment by nfx** [comment]
unfortunately, we cannot endorse any repos outside of databricks github orgs.

let me see if there's something we can do about docker images

**Comment by judahrand** [comment]
> unfortunately, we cannot endorse any repos outside of databricks github orgs.

Oh, I realized that. I made it myself before this project was public.

> let me see if there's something we can do about docker images

That would be really appreciated and would probably allow us to move away from our homegrown SDK!

I am, however, incredibly disappointed that the Databricks OpenAPI definition YAMLs no longer seem to be downloadable.

**Comment by nfx** [comment]
will be fixed the next version
