### ISSUE TITLE
Use the sdk from within databricks?

### ISSUE THREAD

**Issue by btglau** [databricks/databricks-sdk-py#153]
Hello,

I am looking for the simplest to automate submitting a large amount of jobs. I see that databricks_cli https://docs.databricks.com/dev-tools/cli/index.html does not seem to be in active development, so I am looking at this project as a solution for automation.

I would like to be able to run this sdk from within my databricks workspace, but when I try the example https://docs.databricks.com/dev-tools/sdk-python.html#get-started-with-the-databricks-sdk-for-python, I get the error message `default auth: cannot configure default credentials`

I assume that is because databricks-sdk-py is unaware that I am running from within my databricks workspace. My question is, is there a way to make the module recognize that and assume my credentials?

**Comment by mgyucht** [comment]
You're absolutely right. We have work in progress to address this ongoing: https://github.com/databricks/databricks-sdk-py/pull/152.

**Comment by btglau** [comment]
Awesome! I'm getting to the point where I'm launching many jobs from databricks and a programmatic interface is exactly what I need.
