### ISSUE TITLE
Capture resourceType from GET Groups API

### ISSUE THREAD

**Issue by nsenno-dbr** [databricks/databricks-sdk-py#154]
The SCIM Groups API returns a value under `meta.resourceType` which can have a value of `Group` (account level group) or `WorkspaceGroup` (workspace local group). 

Currently, the SDK does not capture this piece of information
```
@dataclass
class Group:
    display_name: str = None
    entitlements: 'List[ComplexValue]' = None
    external_id: str = None
    groups: 'List[ComplexValue]' = None
    id: str = None
    members: 'List[ComplexValue]' = None
    roles: 'List[ComplexValue]' = None
```

Note that the value is present when accessing the API directly 

![image](https://github.com/databricks/databricks-sdk-py/assets/59416974/528327aa-71a9-46e8-a078-3c167c81f781)

I propose we add the `meta.resourceType` field to the Group data class. This functionality is currently leveraged by the [UC-Migration](https://github.com/databricks/UC-Upgrade/blob/b115a24217d14b072dc96801e0bcb9a2fca86fc8/uc_upgrade/group_migration.py#L126) project

Note that I'm happy to make an attempt at contributing this functionality. I don't see any contribution guides for this project.

**Comment by nfx** [comment]
as per discussion: please use 

```
from databricks.sdk import AccountClient
a = AccountClient()
for g in a.groups.list():
  ...
```
