### ISSUE TITLE
'get_run' does not return repair_history when include_history=True

### ISSUE THREAD

**Issue by btglau** [databricks/databricks-sdk-py#175]
Hello,

I am trying to get the id from repair_history, via

`j = w.jobs.get_run(55343378, include_history=True)`

This run, while repaired when I check in the databricks web UI, does not return a repair_history. I do get a list of two tasks, the original, and the repair, as this job only has one task.

**Comment by nfx** [comment]
could you enable debug logging and see if the history is included in the response?

**Comment by btglau** [comment]
I will report back early next week!

**Comment by btglau** [comment]
This seems to be fixed in the latest version, v0.1.11 vs v.0.1.8
