### ISSUE TITLE
databricks-sdk 0.1.10 vs databricks-sdk 0.1.11, metastores call issue???

### ISSUE THREAD

**Issue by Ryujaeyoung** [databricks/databricks-sdk-py#200]
It is the same code, but in databricks sdk 10, the result comes out normally. But in databricks sdk 11 it doesn't give me any result. Please check the sdk 11 issue.
(The host and token information used below are all the same.)

datahub@actions:/tmp/datahub/ingest$ pip list | grep databricks-sdk
databricks-sdk                      0.1.10
datahub@actions:/tmp/datahub/ingest$ python
Python 3.10.10 (main, Mar 14 2023, 02:37:11) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> from databricks.sdk import WorkspaceClient
>>> wc = WorkspaceClient(host="[https://xxx.azuredatabricks.net:443](https://xxx.azuredatabricks.net/)", token="xxx")
>>> wc.metastores.summary()
GetMetastoreSummaryResponse(cloud='azure', created_at=xxxxx, created_by='xxxx', default_data_access_config_id='xxxx', <----- The message appears normally, but the following will be masked for security reasons.

-------------------------------------
datahub@datahub-acryl-datahub-actions-89d9dc966-kjhcd:/$ pip list | grep databricks-sdk
databricks-sdk                      0.1.11
datahub@datahub-acryl-datahub-actions-89d9dc966-kjhcd:/$ python
Python 3.10.10 (main, Mar 14 2023, 02:37:11) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> from databricks.sdk import WorkspaceClient
>>> wc = WorkspaceClient(host="[https://xxxxx.azuredatabricks.net:443](https://xxxxx.azuredatabricks.net/)", token="xxxxx")
>>> wc.metastores.summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/datahub/.local/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", line 4173, in summary
    json = self._api.do('GET', '/api/2.1/unity-catalog/metastore_summary')
  File "/home/datahub/.local/lib/python3.10/site-packages/databricks/sdk/core.py", line 942, in do
    raise self._make_nicer_error(message=message) from None
databricks.sdk.core.DatabricksError: Databricks - Sign In

**Comment by nfx** [comment]
@Ryujaeyoung could you try with 0.1.12? there should be no changes in the SDK that actually change this behavior.

please enable debug logging, and create new issue and attach logs if issue persists in 0.1.12
<img width="1510" alt="Untitled_Notebook_2023-06-28_11_07_59_-_Databricks" src="https://github.com/databricks/databricks-sdk-py/assets/259697/932837f8-da5d-4a59-bb42-f8ceab933e8c">
