### ISSUE TITLE
'Databricks - Sign in' error is thrown when trying to list the metastores

### ISSUE THREAD

**Issue by szabolcs-kun** [databricks/databricks-sdk-py#203]
I'm receiving the following error message when I'm trying to list the metastores of an account:

```
Traceback (most recent call last):
  File "/mnt/c/Users/kunsz/Documents/GitHub/dbx_py_poc/dbxpoc.py", line 15, in <module>
    all = account_client.metastores.list()
  File "/home/skun/.local/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", line 3080, in list
    json = self._api.do('GET', f'/api/2.0/accounts/{self._api.account_id}/metastores')
  File "/home/skun/.local/lib/python3.10/site-packages/databricks/sdk/core.py", line 942, in do
    raise self._make_nicer_error(message=message) from None
databricks.sdk.core.DatabricksError: Databricks - Sign in
```

I'm getting the same error message If I'm trying to pull the corresponding API endpoint (`https://accounts.azuredatabricks.net/api/2.0/accounts/ACCOUNT_ID/metastores`). The solution was to add the `X-Databricks-Account-Console-API-Version: 2.0` header to the request.

I checked the source code, and the inline documentation often mentions the following: "Please add a header X-Databricks-Account-Console-API-Version: 2.0 to access this API." But there needs to be a specification on how to do it. Can you extend the documentation about adding custom headers to the API calls?

Here is my code:
```
from databricks.sdk import WorkspaceClient, AccountClient

a = AccountClient(
    host = "https://accounts.azuredatabricks.net",
    account_id = "....",
    azure_client_id = "....",
    azure_client_secret = "....",
    azure_tenant_id = "....",
    auth_type='azure-client-secret',
)

all = a.metastores.metastores.list()

print(all)
```

**Comment by nfx** [comment]
it's a known issue, we're working on it

**Comment by mgyucht** [comment]
The upstream issue has been fixed: the header is no longer required.

**Comment by de-jaina** [comment]
@mgyucht , @nfx  I am facing a similar issue in the list workspaces at account level. Here is the issue [https://github.com/databricks/databricks-sdk-py/issues/242](https://github.com/databricks/databricks-sdk-py/issues/242).
