### ISSUE TITLE
Creating Scope with Azure KeyVault is not functioning properly

### ISSUE THREAD

**Issue by sahanbah** [databricks/databricks-sdk-py#204]
```
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.workspace import AzureKeyVaultSecretScopeMetadata, ScopeBackendType

DATABRICKS_HOST = <DATABRICKS_HOST>
DATABRICKS_TOKEN = <DATABRICKS_TOKEN>

client = WorkspaceClient(
   host  = DATABRICKS_HOST,
   token = DATABRICKS_TOKEN
)

client.secrets.create_scope(
   scope=<scope_name>,
   initialManagePrincipal = "users",
   scope_backend_type=ScopeBackendType.AZURE_KEYVAULT,
   keyvault_metadata=AzureKeyVaultSecretScopeMetadata(
    resource_id=<resource_id>,
    dns_name=<dns_name>
   )
)
```

**Results in an error**: Traceback (most recent call last):
  File "/databrickssdk.py", line 15, in <module>
    client.secrets.create_scope(
  File "/.venv/lib/python3.10/site-packages/databricks/sdk/service/workspace.py", line 930, in create_scope
    self._api.do('POST', '/api/2.0/secrets/scopes/create', body=body)
  File "/.venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 922, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
databricks.sdk.core.DatabricksError: Scope with Azure KeyVault must have AzureKeyVaultSecretScopeMetadata defined!

**Comment by mgyucht** [comment]
Hi there, thanks for reporting this. Could you please enable debug logging and paste here the debug logs of the request sent to Databricks? I'm working on setting up a reproduction but blocked on some IAM changes, which could take a day or two.

**Comment by nfx** [comment]
@sahanbah `keyvault_metadata` requires that you use azure-native authentication - https://databricks-sdk-py.readthedocs.io/en/latest/authentication.html#azure-native-authentication and you're using PAT tokens (`token` field).
