### ISSUE TITLE
Accessing `__annotations__`

### ISSUE THREAD

**Issue by MichaelSpece** [databricks/databricks-sdk-py#215]
**Description**
`databricks.sdk.core.Config.attributes` is designed for Python 3.9 or less and causes subclassing to fail on higher versions.

**Reproduction**
```py
import databricks.sdk.core


class DatabricksConfig(databricks.sdk.core.Config):
    def __init__(self):
        super().__init__()

DatabricksConfig()
```

**Expected behavior**
Expect no error above.  There would be no error with the recommended way (https://docs.python.org/3/howto/annotations.html) of accessing `__annotations__`.

**Debug Logs**
```shell
Connected to pydev debugger (build 231.9011.38)
Traceback (most recent call last):
  File "...\Lib\site-packages\databricks\sdk\core.py", line 505, in __init__
    self._set_inner_config(kwargs)
  File "...\Lib\site-packages\databricks\sdk\core.py", line 732, in _set_inner_config
    for attr in self.attributes():
                ^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\databricks\sdk\core.py", line 709, in attributes
    anno = cls.__dict__['__annotations__']
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: '__annotations__'
python-BaseException
```

**Other Information**
 - OS: Windows
 - Python version: 3.11.4
 - SDK version: 1.11

**Additional context**
I could push a potential fix.

**Comment by mgyucht** [comment]
Feel free to submit a change!

**Comment by nfx** [comment]
@MichaelSpece what is the use-case for this? do you miss anything in the config?

**Comment by MichaelSpece** [comment]
@nfx The PR #216 that passes Python 3.10-3.11 would not do so without the changes therein irrespective of configuration.

One use case is subclassing `Config` with versions of Python >= 3.10.

Additionally, the changes in #216 make code compliant with the python documentation linked above.
