### ISSUE TITLE
[ISSUE] Workspace Assignment Update Permission

### ISSUE THREAD

**Issue by jaina15** [databricks/databricks-sdk-py#254]
**Description**
I was using workspace assignment update method and it was working fine until yesterday. But I started facing issue in the same code from today onwards.

Here is the code piece:
```
a = AccountClient(
  host                = "https://accounts.azuredatabricks.net",
  account_id          = "account_id",
  azure_tenant_id     = "azure_tenant_id",
  azure_client_id     = "azure_client_id",
  azure_client_secret = "azure_client_secret",
  auth_type           = "azure-client-secret"
)
a.workspace_assignment.update(permissions = ['USER'],workspace_id=123456789,principal_id=987654321)
```

**Error**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File <command-4410515509942231>:1
----> 1 a.workspace_assignment.update(permissions = ['USER'],workspace_id=123456789,principal_id=987654321)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-8112d010-5896-4545-b12c-d7023873c5a4/lib/python3.9/site-packages/databricks/sdk/service/iam.py:2613, in WorkspaceAssignmentAPI.update(self, permissions, workspace_id, principal_id, **kwargs)
   2609 if not request: # request is not given through keyed args
   2610     request = UpdateWorkspaceAssignments(permissions=permissions,
   2611                                          principal_id=principal_id,
   2612                                          workspace_id=workspace_id)
-> 2613 body = request.as_dict()
   2614 self._api.do(
   2615     'PUT',
   2616     f'/api/2.0/accounts/{self._api.account_id}/workspaces/{request.workspace_id}/permissionassignments/principals/{request.principal_id}',
   2617     body=body)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-8112d010-5896-4545-b12c-d7023873c5a4/lib/python3.9/site-packages/databricks/sdk/service/iam.py:813, in UpdateWorkspaceAssignments.as_dict(self)
    811 def as_dict(self) -> dict:
    812     body = {}
--> 813     if self.permissions: body['permissions'] = [v.value for v in self.permissions]
    814     if self.principal_id is not None: body['principal_id'] = self.principal_id
    815     if self.workspace_id is not None: body['workspace_id'] = self.workspace_id

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-8112d010-5896-4545-b12c-d7023873c5a4/lib/python3.9/site-packages/databricks/sdk/service/iam.py:813, in <listcomp>(.0)
    811 def as_dict(self) -> dict:
    812     body = {}
--> 813     if self.permissions: body['permissions'] = [v.value for v in self.permissions]
    814     if self.principal_id is not None: body['principal_id'] = self.principal_id
    815     if self.workspace_id is not None: body['workspace_id'] = self.workspace_id

AttributeError: 'str' object has no attribute 'value'
```

**Additional context**
It was working fine until yesterday. I can see some changes have been pushed yesterday to the sdk. Looks like there is some change with permissions parameter but the [doc ](https://docs.databricks.com/api/azure/account/workspaceassignment/update) states it's **permissions required Array of strings**

**Comment by slowder-bpcs** [comment]
Where did you get using permissions = ['USER'], rather than  permissions=[iam.WorkspacePermission.USER] like https://databricks-sdk-py.readthedocs.io/en/latest/account/workspace_assignment.html demonstrates?  That fixed the problem I was having with workspace_assignment.update.  I suspect something was changed in their update implementation, but I don't know what.

**Comment by jaina15** [comment]
Ahh, I was looking at this [https://docs.databricks.com/api/azure/account/workspaceassignment/update](https://docs.databricks.com/api/azure/account/workspaceassignment/update). There is a request sample in the right, I was following that.
![image](https://github.com/databricks/databricks-sdk-py/assets/26425486/d0a96a39-1b9e-4973-840b-bebac3756462)

**Comment by slowder-bpcs** [comment]
I'll have to start checking that documentation and the "read the docs" site. I wish the documentation were clearer and in one place.  It's hard to know when to use the REST API values and when to use the python data classes and enums.  Maybe it's just me who struggles with this.
