### ISSUE TITLE
[FEATURE] Add Unity Catalog groups to Databricks workspace

### ISSUE THREAD

**Issue by Sean10000** [databricks/databricks-sdk-py#257]
**Problem Statement**
we are developing Databricks IAC, but we cannot find a function to add the UC groups to Databricks workspace via Databricks python SDK so far for our initialization Databricks IAC jobs.
**Proposed Solution**
Support add uc groups to databricks workspace via databricks python sdk.

**Comment by Sean10000** [comment]
it's a key step to add user group from databrick account to workspace, impact following authentication & authorization, we don't want maintain the groups in both sides.

**Comment by jaina15** [comment]
@Sean10000 , isn't [https://docs.databricks.com/api/azure/account/workspaceassignment/update](https://docs.databricks.com/api/azure/account/workspaceassignment/update) this satisfying your use case? I was also trying to allocate permission to users/groups from UC to different workspaces and it's working fine for me. In SDK you can use **update** method under **workspace_assignment** like below:

```
from databricks.sdk import AccountClient
from databricks.sdk.service import iam

a = AccountClient(
  host                = "https://accounts.azuredatabricks.net",
  account_id          = "account_id",
  azure_tenant_id     = "azure_tenant_id",
  azure_client_id     = "azure_client_id",
  azure_client_secret = "azure_client_secret",
  auth_type           = "azure-client-secret"
)
a.workspace_assignment.update(permissions = ['iam.WorkspacePermission.USER'],workspace_id=0987654321,principal_id=123456789)
```

**Comment by Sean10000** [comment]
> @Sean10000 , isn't https://docs.databricks.com/api/azure/account/workspaceassignment/update this satisfying your use case? I was also trying to allocate permission to users/groups from UC to different workspaces and it's working fine for me. In SDK you can use **update** method under **workspace_assignment** like below:
> 
> ```
> from databricks.sdk import AccountClient
> from databricks.sdk.service import iam
> 
> a = AccountClient(
>   host                = "https://accounts.azuredatabricks.net",
>   account_id          = "account_id",
>   azure_tenant_id     = "azure_tenant_id",
>   azure_client_id     = "azure_client_id",
>   azure_client_secret = "azure_client_secret",
>   auth_type           = "azure-client-secret"
> )
> a.workspace_assignment.update(permissions = ['iam.WorkspacePermission.USER'],workspace_id=0987654321,principal_id=123456789)
> ```

That works. Many thanks for your help @jaina15
