### ISSUE TITLE
Cannot import sql from databricks

### ISSUE THREAD

**Issue by daanschonberger** [databricks/databricks-sdk-py#288]
**Description**
After pip installing the `databricks-sql-connector` in a notebook as described in https://learn.microsoft.com/en-us/azure/databricks/dev-tools/python-sql-connector we get a dependency issue between certain packages
<img width="598" alt="pip_dep" src="https://github.com/databricks/databricks-sdk-py/assets/59645624/27214b23-4f57-4fd9-8351-dc37d184e4bc">

After this we have a ModuleNotFoundError,
<img width="535" alt="cannot_import" src="https://github.com/databricks/databricks-sdk-py/assets/59645624/1e1025de-2eab-4b73-8959-58c2951b3c78">

 but it can autocomplete the desired module
![image](https://github.com/databricks/databricks-sdk-py/assets/59645624/13841280-a89d-438f-b538-f7a6330196d6)

**Reproduction**
`pip install databricks-sql-connect`

**Expected behavior**
3 months ago I used the same code and it worked fine to install the package and use the `sql` module, while now it can't import it.

**Other Information**
 - Databricks cluster runtime 13.2
 - Databricks-sdk Version: 0.1.6 & 0.5.0(both failed)

**Comment by mgyucht** [comment]
Sorry about this! The default version of the SDK installed on DBR 13.2 is 0.1.6. I was able to reproduce this according to your instructions.

To mitigate, you should be able to run 
```
%pip install databricks-sdk -U
```
followed by 
```
%pip install databricks-sql-connector
```
and then
```
dbutils.library.restartPython()
```
to upgrade the SDK and install the SQL connector.

Please let me know if this solves your problem.

**Comment by daanschonberger** [comment]
Thanks for the swift response and great explanation, works like a charm!
