### ISSUE TITLE
[ISSUE] Can't import WorkspaceClient

### ISSUE THREAD

**Issue by james-camacho-ab** [databricks/databricks-sdk-py#297]
**Description**
Attempting to use the WorkspaceClient class, but unable to import it into my Databricks Workspace environment
**Reproduction**
A minimal code sample demonstrating the bug.
![image](https://github.com/databricks/databricks-sdk-py/assets/85585586/c4ebe743-e07b-4453-b590-b48adbbc6c26)

**Expected behavior**
No ImportError
**Debug Logs**
The SDK logs helpful debugging information when debug logging is enabled. Set the log level to debug by adding `logging.basicConfig(level=logging.DEBUG)` to your program, and include the logs here.
See screenshot
**Other Information**
 - OS: [e.g. macOS]
 - Version: [e.g. 0.1.0]

**Additional context**
Databricks was able to predict the text for WorkspaceClient in the import statement, so it seems to know that it's there. Not sure why it can't import

**Comment by nfx** [comment]
Use “%pip install”, not “%sh pip install”.
