### ISSUE TITLE
[FEATURE] Add `py.typed`

### ISSUE THREAD

**Issue by smackesey** [databricks/databricks-sdk-py#310]
**Problem Statement**
This library's types are not picked up by some language servers (pyright) by default because the package does not include a `py.typed` file.

**Proposed Solution**
From what I can tell the library is fully or almost fully typed, so it should include `py.typed`.

**Additional Context**
See [PEP 561](https://peps.python.org/pep-0561/) for more info on `py.typed`.

**Comment by icj217** [comment]
I believe this was addressed: https://github.com/databricks/databricks-sdk-py/releases/tag/v0.16.0

**Comment by smackesey** [comment]
Fixed in 0.16.0.
