### ISSUE TITLE
Unable to add permissions to a workspace instance profile

### ISSUE THREAD

**Issue by andy-potter-evotix** [databricks/databricks-sdk-py#320]
There does not appear to be any way to add permissions to a workspace instance profile using the SDK. 

We have a setup process which creates a service principal which is used by a Job as the 'run as' principal. When our jobs are created they fail to run because the job cluster uses an instance profile and the service principal does not have access to use the instance profile. We want our setup process to add the permission using the Databricks Python SDK but there doesn't appear to be a method for doing this

**Comment by mgyucht** [comment]
Do you see the API you're interested in at https://docs.databricks.com/api/workspace/permissions? If not, then there is no API for this today.

**Comment by andy-potter-evotix** [comment]
Hey @mgyucht. No I don't see an API for Instance Profiles in the list under  [](https://docs.databricks.com/api/workspace/permissions). Does this mean there is no way to amend the permissions for an instance profile via the Databricks API. This will be a problem for us as our clusters use instance profiles to be able to access AWS S3 buckets where data is stored. If we can't grant permission to use the instance profile to the service principal that our Job runs as then the job fails to run.

**Comment by pietern** [comment]
To manage permissions for instance profiles you need to use the SCIM APIs: https://docs.databricks.com/en/aws/iam/manage-instance-profiles.html#manage-access-to-instance-profiles-using-the-api. We don't have a wrapper for these operations at the moment.

**Comment by andy-potter-evotix** [comment]
Thanks @pietern using the SCIM APIs worked me. In this case I used the SDKs service principal patch method like this:
`    workspace_client.service_principals.patch(
        job_principal.id,
        schemas=[db_iam.PatchSchema.URN_IETF_PARAMS_SCIM_API_MESSAGES_2_0_PATCH_OP],
        operations=[db_iam.Patch(op=db_iam.PatchOp.ADD, path="roles", value=[{"value":instance_profile.instance_profile_arn}])]
    )`
