### ISSUE TITLE
[FEATURE] DLT pipeline updates should not require a full payload

### ISSUE THREAD

**Issue by mberk06** [databricks/databricks-sdk-py#323]
**Problem Statement**
DLT pipeline updates require you specify a valid payload config, which adds a lot of burden on the user. 
<img width="1366" alt="image" src="https://github.com/databricks/databricks-sdk-py/assets/18635689/a6a3dc4c-8336-4e7b-a0b9-b712bca6161b">

**Proposed Solution**
Automatically do a pipeline GET before UPDATE to fill all unspecified arguments.

**Additional Context**
I assume we will have the same issue for other workspace objects.

**Comment by mberk06** [comment]
My current workaround (running in Field Eng workspace)
```
import inspect
from typing import Dict
from databricks.sdk import WorkspaceClient

def safe_extract_kwargs(obj: object, attribute: str) -> object:
  try:
    return getattr(obj, attribute)
  except AttributeError as e:
    return None
  except:
    raise

def convert_object_to_kwargs(target_function: callable, source_object: object) -> Dict:
    target_function_parameters = set(inspect.signature(target_function).parameters.keys())

    kwargs = {k: safe_extract_kwargs(source_object, k) for k in target_function_parameters}
    return {k:v for k,v in kwargs.items() if v is not None}
  
w = WorkspaceClient()
instance = w.pipelines.get('5c87f9dc-89f6-43ec-998e-63f73aa90594').spec
convert_object_to_kwargs(w.pipelines.update, instance)
```

<img width="1412" alt="image" src="https://github.com/databricks/databricks-sdk-py/assets/18635689/62b8f086-2369-4446-a909-653550ceabbd">

**Comment by mgyucht** [comment]
IMO this is a feature request for DLT update. We aren't doing anything fancy in the SDK other than providing convenient methods for you to use to call the REST API. I would suggest following-up with the DLT team to see if they can expose an API accepting partial updates via a PATCH command.
