### ISSUE TITLE
[FEATURE] Use databricks secrets in configuration strings, especially URLs

### ISSUE THREAD

**Issue by julianfesel** [databricks/databricks-sdk-py#330]
**Problem Statement**
It is not possible to reference databricks secrets in the repository url for a pypi task:
```
PythonPyPiLibrary(
package="oebb-tt-ttop-dbx-drs",
repo="https://user:{{secrets/scope/token}}@repository/bla/"
)
```
This leads to the error:
`databricks.sdk.core.DatabricksError: Could not parse URI. Please double check your input.`

**Proposed Solution**
There should be a clear way how to use databricks secrets with the sdk.

**Comment by pietern** [comment]
This is not something we should do in the SDK, as you'd want these to be resolved when they are used (server side).

This is a platform-side feature request. Please get in touch with your SA / representative to track it.

**Comment by julianfesel** [comment]
> This is not something we should do in the SDK, as you'd want these to be resolved when they are used (server side).
> 
> This is a platform-side feature request. Please get in touch with your SA / representative to track it.

Thanks for the response! I think I did not make this case clear and actually I should probably have labeled it as an ISSUE.
I do not want the secret to be resolved by the sdk but to simple be able to reference it in the URL. It seems though that the sdk does not allow me to do that and using a secret in the URL leads to the mentioned error message. 
To state once more in other words: I just want to be able to reference an existing secret in the url of the repository.
