### ISSUE TITLE
[ISSUE] Delete service principal secret doesn't work

### ISSUE THREAD

**Issue by andy-potter-evotix** [databricks/databricks-sdk-py#350]
**Description**
The 'delete' method of the ServicePrincipalSecretsAPI class doesn't actually delete the service principal secret. This is due to a typo in the request URL format string in the delete method (there is an extra comma at the end of the string).

**Reproduction**
To reproduce the issue simply call the delete method of the ServicePrincipalSecretsAPI  with a valid principal id and secret id. Once called use the 'list' method to verify that the secret hasn't actually been deleted.
```
account_client.service_principal_secrets.delete(job_principal.id, secret.id)
````

**Expected behavior**
The specified secret is deleted once the method returns.

**Fix**
Remove the errorneous extra comma at the end of the URL format string in the 'delete' method of the ServicePrincipalSecretsAPI.
```
            f'/api/2.0/accounts/{self._api.account_id}/servicePrincipals/{service_principal_id}/credentials/secrets/{secret_id},',
```

**Comment by andy-potter-evotix** [comment]
For anyone needing a workaround for this you can define your own local method which uses the undelying _api.do method:
```
# This method is based on the 'delete' method from the ServicePrincipalSecretsAPI class in the Databricks SDK file:
# https://github.com/databricks/databricks-sdk-py/blob/main/databricks/sdk/service/oauth2.py
# we have customised as the original method has an incorrect URL string
def delete_service_principal_secret(account_client: AccountClient, service_principal_id: int, secret_id: str):
    headers = {}
    account_client.service_principal_secrets._api.do(
        'DELETE',
        f'/api/2.0/accounts/{account_client.service_principal_secrets._api.account_id}/servicePrincipals/{service_principal_id}/credentials/secrets/{secret_id}',
        headers=headers)
```

**Comment by mgyucht** [comment]
Thanks for reporting this. We're making a fix upstream in our internal API definition, and the fix will be published in the next version of the SDK next week.

**Comment by mgyucht** [comment]
The spec fix has been merged. The next Py SDK release next week will include the fix.

**Comment by mgyucht** [comment]
@andy-potter-evotix This issue has been fixed in the latest release of the Python SDK. Thanks for reporting this!
