### ISSUE TITLE
SDK is failing in Staging

### ISSUE THREAD

**Issue by FastLee** [databricks/databricks-sdk-py#352]
**Description**
Attempting to run Workspace SDK in our staging environment generate an error, ValueError: Not a valid Semver 

**Reproduction**
run clusters.select_spark_version(latest=True)

**Expected behavior**
I expected it to work similar to any other workspace.

**Debug Logs**
The SDK logs helpful debugging information when debug logging is enabled. Set the log level to debug by adding `logging.basicConfig(level=logging.DEBUG)` to your program, and include the logs here.

**Other Information**
 - WS: https://e2-dogfood-unity-catalog-us-east-1.staging.cloud.databricks.com/

**Additional context**
![image](https://github.com/databricks/databricks-sdk-py/assets/10814065/78aed18a-0ca8-40da-9ced-5437e4095da2)

**Comment by mgyucht** [comment]
Thanks for reporting this @FastLee! Given that this only impacts staging, this is a lower priority issue for us to look into. As a workaround for now, you can list spark versions directly and pick the version you want from the response.
