### ISSUE TITLE
[ISSUE] Unable to retrieve the return value of the list method in TablesAPI class

### ISSUE THREAD

**Issue by manabian-** [databricks/databricks-sdk-py#379]
**Description**
I am unable to retrieve the return value of the list method in the TablesAPI class. 

**Reproduction**

```python
import time

from databricks.sdk import WorkspaceClient

w = WorkspaceClient()

created_catalog = w.catalogs.create(name=f'sdk-{time.time_ns()}')

created_schema = w.schemas.create(name=f'sdk-{time.time_ns()}', catalog_name=created_catalog.name)

all_tables = w.tables.list(catalog_name=created_catalog.name, schema_name=created_schema.name)
print(all_tables)

# cleanup
w.schemas.delete(full_name=created_schema.full_name)
w.catalogs.delete(name=created_catalog.name, force=True)
```

<img width="408" alt="image" src="https://github.com/databricks/databricks-sdk-py/assets/10123723/0d5b280f-8d13-4a90-a551-5d698c6ff62d">

**Expected behavior**
Gets an array of all tables for the current metastore under the parent catalog and schema. 

**Other Information**
 - Enviroment: Azure Databricks 
 - Runtime Version: 13.3 LTS ML (includes Apache Spark 3.4.1, Scala 2.12)

**Additional context**

Could it be that the reason is that the return value of the method has not been set? It seems that the list_summaries method also does not have a return value set.

https://github.com/databricks/databricks-sdk-py/blob/bbe81c13c4a0275020d241b78f61cdddf349adc2/databricks/sdk/service/catalog.py#L5525-L5533

**Comment by mgyucht** [comment]
This method returns a generator. If you want to turn it into a list, you can do `list(all_tables)`. Please reopen if you have issues with this.

**Comment by manabian-** [comment]
Thank you for your response. By making the following changes, it worked as expected.I appreciate your help.

```python
import time

from databricks.sdk import WorkspaceClient

w = WorkspaceClient()

created_catalog = w.catalogs.create(name=f"sdk-{time.time_ns()}")
created_schema = w.schemas.create(
    name=f"sdk-{time.time_ns()}",
    catalog_name=created_catalog.name,
)
spark.sql(
    f"""
    CREATE TABLE `{created_catalog.name}`.`{created_schema.name}`.table_01
    """
)

all_tables = w.tables.list(
    catalog_name=created_catalog.name, schema_name=created_schema.name,
)
print(list(all_tables))

# cleanup
w.schemas.delete(full_name=created_schema.full_name)
w.catalogs.delete(name=created_catalog.name, force=True)
```

<img width="760" alt="image" src="https://github.com/databricks/databricks-sdk-py/assets/10123723/a5a5f9cc-1e44-4e52-8777-2819285741f7">
