### ISSUE TITLE
Warehouse Config set up failing with databricks.sdk.core.DatabricksError: enable_serverless_compute is required.

### ISSUE THREAD

**Issue by dipankarkush-db** [databricks/databricks-sdk-py#416]
I am trying to create a warehouse config -

```
w.warehouses.set_workspace_warehouse_config(data_access_config=[EndpointConfPair(
    key="spark.databricks.dataLineage.enabled", value="true"
)], security_policy=SetWorkspaceWarehouseConfigRequestSecurityPolicy.DATA_ACCESS_CONTROL,
    enabled_warehouse_types=[
        WarehouseTypePair(enabled=True, warehouse_type=WarehouseTypePairWarehouseType.TYPE_UNSPECIFIED)]
)
```

and getting this error - `databricks.sdk.core.DatabricksError: enable_serverless_compute is required.`

there is no enable_serverless_compute parameter in the set_workspace_warehouse_config() function.

**Comment by mgyucht** [comment]
This duplicates https://github.com/databricks/databricks-sdk-py/issues/305, so I will close this in favor of that other ticket.
