### ISSUE TITLE
[ISSUE] WorkspaceClient.jobs.create() with edit_mode = CreateJobEditMode.UI_LOCKED not creating a locked job

### ISSUE THREAD

**Issue by randall-gonzalez-dbx** [databricks/databricks-sdk-py#446]
**Description**
WorkspaceClient.jobs.create() with edit_mode = CreateJobEditMode.UI_LOCKED not creating a locked job. The job is still editable through the UI.

**Is it a regression?**
I did not get to test it in previous versions of the SDK.

**Comment by mgyucht** [comment]
I'll raise with the corresponding team. However, can you include debug logs so we can see the request/response?

**Comment by mgyucht** [comment]
This feature is not yet released to all production workspaces. You can follow the [release notes of Databricks](https://docs.databricks.com/en/release-notes/product/index.html) to see when this feature is in public preview and available to all workspaces.
