### ISSUE TITLE
[ISSUE] Python SDK doesn't allow catalog rename but REST api does

### ISSUE THREAD

**Issue by johnayoub** [databricks/databricks-sdk-py#447]
**Description**
Catalog cannot be renamed via the python SDK but it's possible via the REST API

**Reproduction**
N/A

**Expected behavior**
Rename catalog

**Is it a regression?**
N/A

**Debug Logs**
N/A

**Other Information**
 - Version: 0.13.0

**Additional context**

The SDK doesn't accept full name and name to be updated.

SDK

![image](https://github.com/databricks/databricks-sdk-py/assets/9760128/2dc03894-a40f-4ec5-ada9-cbf7da5ff3ec)

REST API

![image](https://github.com/databricks/databricks-sdk-py/assets/9760128/3d1fc68b-f4a4-4e4d-be88-b5dacea54f75)

As you can see name is missing from the SDK body

**Comment by mgyucht** [comment]
Thanks for reporting. We're aware of this issue and are working with the UC team to fix their API specification to support UC resource renaming consistently for catalogs and other UC resources.

**Comment by mgyucht** [comment]
This should be fixed in the latest SDK version. You can now specify `new_name` for the catalog. This fix was released for other UC resources whose path parameter is called `name`.
