### ISSUE TITLE
[ISSUE] Databricks Python SDK Group API always returns `None` as members in Azure Account

### ISSUE THREAD

**Issue by keyunjie96** [databricks/databricks-sdk-py#451]
**Description**
 Databricks Python SDK Group API always returns zero members in Azure Account. No issues in AWS.

**Reproduction**

AWS returns normal results
```Python
aws_account_client = AccountClient(
    host="https://accounts.cloud.databricks.com/",
    account_id="[REDACTED]",
    client_id="[REDACTED]",
    client_secret=dbutils.secrets.get(scope="[REDACTED]", key="[REDACTED]"),
)
aws_account_client.groups.list()
```
```Bash
[
Group(display_name='[REDACTED]', entitlements=None, external_id=None, groups=None, id='[REDACTED]', members=[ComplexValue(display='[REDACTED]', primary=None, type=None, value='[REDACTED]'), ComplexValue(display='[REDACTED]', primary=None, type=None, value='[REDACTED]'), ...], meta=None, roles=None),
...
]
```

What Azure returns has always `None` as `members`.
```Python
azure_account_client = AccountClient(
    host="https://accounts.azuredatabricks.net/",
    account_id="[REDACTED]",
    azure_tenant_id="[REDACTED]",
    azure_client_id="[REDACTED]",
    azure_client_secret=dbutils.secrets.get(scope="[REDACTED]", key="[REDACTED]"),
)
azure_account_client.groups.list()
```

```Bash
[
Group(display_name='[REDACTED]', entitlements=None, external_id=None, groups=None, id='[REDACTED]', members=None, meta=None, roles=None),
...
]
```

We keep the AWS Databricks account and Azure Databricks account in the same group membership (pushed and synced from one identity provider), which I have verified multiple times. 

However, it always returns `None` as members. And if the target group really has zero members, it should return an empty list, not `None`, right? It makes me think that this is a bug. 

**Expected behavior**
* Groups API should return non-None `members` at least for a non-empty group

**Is it a regression?**
* Tested it in both `v0.6.0` and `v.0.13.0`

**Debug Logs**
After setting logging to `DEBUG` 
```Python
logging.basicConfig(level=logging.DEBUG)
azure_account_client = AccountClient(
    host="https://accounts.azuredatabricks.net/",
    account_id="[REDACTED]",
    azure_tenant_id="[REDACTED]",
    azure_client_id="[REDACTED]",
    azure_client_secret=dbutils.secrets.get(scope="[REDACTED]", key="[REDACTED]"),
)
azure_account_client.groups.list()

```
outputs
```Bash
2023-11-21 20:14:17 INFO [databricks.sdk] Configured AAD token for Service Principal ([REDACTED])
```

**Other Information**
 - OS: from `DBR 11.3 LTS`
 - Version: `databricks-sdk` `0.13.0`

**Additional context**

**Comment by nfx** [comment]
that's exactly why https://github.com/databricks/databricks-sdk-py/pull/361 exists
