### ISSUE TITLE
[ISSUE] no way to provide timeout, requests periodically hanging

### ISSUE THREAD

**Issue by Willem-J-an** [databricks/databricks-sdk-py#487]
**Description**
The SDK does [not seem to support configuring HTTP timeout](https://github.com/databricks/databricks-sdk-py/blob/358126eb49904809408b6f077066655d7eafea8d/databricks/sdk/core.py#L1222C1-L1229C53) which results in some requests hanging.

Example here, this request is now hanging for 50 minutes.
![2023-12-20_17-46](https://github.com/databricks/databricks-sdk-py/assets/51120533/f86846f1-059a-4716-b437-fc1846286250)

[Config item http_timeout_seconds](https://databricks-sdk-py.readthedocs.io/en/latest/authentication.html) (supposed default 60s) does not really seem to be used anywhere in the code.

**Reproduction**
The behaviour is flaky, but I periodically get the issue with the following code:
```python
        _client.statement_execution.execute_statement(
            statement,
            self._warehouse_id,
            disposition=Disposition.EXTERNAL_LINKS,
            format=Format.JSON_ARRAY,
            wait_timeout="50s",
            on_wait_timeout=ExecuteStatementRequestOnWaitTimeout.CONTINUE,
        )
```

**Expected behavior**
Would expect timeout after ~50 sec. If something is wrong, would expect to let me configure some generic HTTP timeout somewhere that would prevent requests from hanging.

**Is it a regression?**
Probably not.

**Debug Logs**
The SDK logs helpful debugging information when debug logging is enabled. Set the log level to debug by adding `logging.basicConfig(level=logging.DEBUG)` to your program, and include the logs here.

**Other Information**
 - OS: linux
 - Version: 0.15.0

**Comment by mgyucht** [comment]
Thanks for reporting! Easy fix to feed this through.
