### ISSUE TITLE
[ISSUE]  sdk job  how to fetch the paramteres which are passed in NotebookTask

### ISSUE THREAD

**Issue by shivatharun** [databricks/databricks-sdk-py#503]
let's say in Main.py file we are creating jobs using sdk.service.

Notebook_name=**Main.py**
 will pass notebook path to run another notebook in:  NotebookTask ( notebook_path='test_run_py',,parameter=dict({"a":1,"b":2})

in test_run_py file how we can fetch those parameter 
Notebook_name= **test_run_py**
please share the code  to fetch those parameter  like a, b and these are constants for the entire code of this notebook

**Comment by mgyucht** [comment]
I think you're looking for the task values API: https://docs.databricks.com/en/workflows/jobs/share-task-context.html. Can you try this?

**Comment by mgyucht** [comment]
Are you looking for this? https://docs.databricks.com/en/workflows/jobs/create-run-jobs.html#pass-parameters-to-a-databricks-job-task

> Parameters set the value of the [notebook widget](https://docs.databricks.com/en/notebooks/widgets.html) specified by the key of the parameter.

From https://docs.databricks.com/en/notebooks/widgets.html:

> You can access the current value of the widget with the call:
```
dbutils.widgets.get("state")
```

**Comment by shivatharun** [comment]
This worked thanks
