### ISSUE TITLE
[ISSUE]  DATABRICK SDK , how to pass output of  one notebook to another notebook as input

### ISSUE THREAD

**Issue by shivatharun** [databricks/databricks-sdk-py#510]
Let say, 
I have created job name: test and 3 tasks.
task1 will perform transformation and provide output. this ouput should be passed to task2 notebook input,
and task2 notebook will provide output  with 3 different values. then task3 has notebook has to take 3 input values should run parallel/independently  with the same notebook.

Can you provide any references to capture pass output values as parameter to another notebook. and to caputre in the run time.?

**Comment by zyd14** [comment]
Might be relevant - https://docs.databricks.com/en/workflows/jobs/share-task-context.html

**Comment by fjakobs** [comment]
The linked documentation should answer the question. Closing as it is unrelated to the SDK
