### ISSUE TITLE
[ISSUE]  Cannot use AccountClient commands after creating a new WorkspaceClient

### ISSUE THREAD

**Issue by william-conti** [databricks/databricks-sdk-py#529]
**Description**
When we have an AccountClient object, and when we create a WorkspaceClient object, all next calls to the AccountClient won't work.

**Reproduction**
```
    def client_for(self, workspace: Workspace) -> WorkspaceClient:
        config = self._ac.config.as_dict()
        if "databricks_cli_path" in config:
            del config["databricks_cli_path"]
        cloud = self._get_cloud()
        # copy current config and swap with a host relevant to a workspace
        config["host"] = f"https://{workspace.deployment_name}.{self._tlds[cloud]}"
        return WorkspaceClient(**config, product="ucx", product_version=__version__)

   def test_broken(self):
        self._ac.groups.create(display_name="test_1")
        for ws in self._ac.workspaces.list():
            client = self.client_for(ws)
            self._ac.groups.create(display_name="test_12")
```

**Expected behavior**
The call to `self._ac.groups.create(display_name="test_12")` should work, but in this case it's raising the error highlighted below.

**Debug Logs**
databricks.sdk.errors.mapping.NotFound: Endpoint not found for /2.0/accounts/2cffc3ba-0e89-463a-a7ec-8161b437db24/scim/v2/Groups

**Additional context**
After debugging, the first call is using the Account URL but the second call is using a workspace URL
I could make it work by using the following code:

```
def test_broken(self):
    from copy import deepcopy

    copy_acc_client = deepcopy(self._ac)
    self._ac.groups.create(display_name="test_1")
    for ws in self._ac.workspaces.list():
        client = self.client_for(ws)
        copy_acc_client.groups.create(display_name="test_12")
```

**Comment by mgyucht** [comment]
@william-conti `config.as_dict()` returns a reference to the same config object. Modifying the host there modifies the config used by AccountClient. You can mitigate this by just using `config.copy()` instead of `config.as_dict()`.

FYI: v0.19.0 will include `AccountClient.get_workspace_client()` which will handle this for you by making a deep copy of the config. With this update, you won't need to maintain your `client_for()` function anymore.

**Comment by william-conti** [comment]
@mgyucht The fix still doesn't work:

```
    def test_broken(self):
        self._ac.groups.create(display_name="test_xxxx")
        for ws in self._ac.workspaces.list():
            ss = self._ac.get_workspace_client(ws)
            self._ac.groups.create(display_name="test_1xxxxx")
```

It yields the same below error:

```
../src/databricks/labs/ucx/account.py:108: in test_broken
    self._ac.groups.create(display_name="test_1xxxxx")
../../../Library/Application Support/hatch/env/virtual/databricks-labs-ucx/-POo8FxM/databricks-labs-ucx/lib/python3.11/site-packages/databricks/sdk/service/iam.py:1374: in create
    res = self._api.do('POST',
../../../Library/Application Support/hatch/env/virtual/databricks-labs-ucx/-POo8FxM/databricks-labs-ucx/lib/python3.11/site-packages/databricks/sdk/core.py:128: in do
    return retryable(self._perform)(method,
../../../Library/Application Support/hatch/env/virtual/databricks-labs-ucx/-POo8FxM/databricks-labs-ucx/lib/python3.11/site-packages/databricks/sdk/retries.py:54: in wrapper
    raise err
../../../Library/Application Support/hatch/env/virtual/databricks-labs-ucx/-POo8FxM/databricks-labs-ucx/lib/python3.11/site-packages/databricks/sdk/retries.py:33: in wrapper
    return func(*args, **kwargs)

E               databricks.sdk.errors.platform.NotFound: Endpoint not found for /2.0/accounts/None/scim/v2/Groups

../../../Library/Application Support/hatch/env/virtual/databricks-labs-ucx/-POo8FxM/databricks-labs-ucx/lib/python3.11/site-packages/databricks/sdk/core.py:221: NotFound
```

**Comment by mgyucht** [comment]
@william-conti is this still an issue? I believe this has been addressed by https://github.com/databricks/databricks-sdk-py/commit/9af2630672c866610248243eb53898c16c452960. Closing this out preemptively, but feel free to reopen if you're still affected.

**Comment by bogumilFajfer** [comment]
This is still the an issue. 
Pretty simple to reproduce. 

ac = AccountClient(
    host="https://myhost.cloud.databricks.com",
    token=token,
    account_id="my_account_id",
)
ac.groups.create(display_name="test_11042025")
databricks.sdk.errors.platform.NotFound: Endpoint not found for /2.0/accounts/my_account_id/scim/v2/Groups
