### ISSUE TITLE
[ISSUE] Import "databricks.sdk" could not be resolved error in VSCode after sdk installation via pip

### ISSUE THREAD

**Issue by albertnjoku** [databricks/databricks-sdk-py#601]
After installing the databricks sdk using "pip install databricks-sdk" and all went successfully. I pasted one of the example codes to try out. However I am getting an error on the line:

`from databricks.sdk import WorkspaceClient`

The error says:

_Import "databricks.sdk" could not be resolved_

For some reasons, VsCode is unable to see the sdk installation.

I am doing this in VSCode

I am trying this in Windows 10 and Python 3.8.5

**Comment by albertnjoku** [comment]
not an issue. code editor setup issue.

**Comment by echakraborty-bread** [comment]
how did this get resolved, I am also getting the same issue , I ran pip install sdk from command line , yet it was saying that databricks.sdk could not be resolved, later I did pip install , and I am getting syntax error
