### ISSUE TITLE
Module 'databricks.sdk.service.sharing' has no attribute 'ListRecipientsRequest'

### ISSUE THREAD

**Issue by Jessy-Chahal** [databricks/databricks-sdk-py#613]
**Description**
I am following the databricks sdk examples to list recipients but I come across this error: 
An error occurred: module 'databricks.sdk.service.sharing' has no attribute 'ListRecipientsRequest'

**Reproduction**
https://github.com/databricks/databricks-sdk-py/blob/main/examples/recipients/list_recipients.py
```
from databricks.sdk import WorkspaceClient
from databricks.sdk.service import sharing

w = WorkspaceClient()

all = w.recipients.list(sharing.ListRecipientsRequest())
```

**Comment by cezhunter** [comment]
try just doing `w.recipients.list()` without passing the `sharing.ListRecipientsRequest()`
