### ISSUE TITLE
OAuth Cross-origin error

### ISSUE THREAD

**Issue by andrefurlan-db** [databricks/databricks-sdk-py#68]
Getting `Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'http://localhost:8020/'.` when using OAuth client with Azure.

It works if I remove the code for both u2m and m2m:
```python
        if 'microsoft' in self._client.token_url:
            # Tokens issued for the 'Single-Page Application' client-type may
            # only be redeemed via cross-origin requests
            headers = {'Origin': self._client.redirect_url}
```

**Comment by nfx** [comment]
@andrefurlan-db in the requirements document you've provided, you emphasised about PKCE everywhere ;)

**Comment by andrefurlan-db** [comment]
Yes, like I mentioned, removing the Origin header fixes the issue and it works with PKCE. I don't understand what is this about?

**Comment by nfx** [comment]
I'll cut a release on Friday (CET) with the fix for this

**Comment by andrefurlan-db** [comment]
Thanks!
