### ISSUE TITLE
[ISSUE] Error with w.shares.share_permissions function / PermissionsList class not defined

### ISSUE THREAD

**Issue by metalcore-labs** [databricks/databricks-sdk-py#683]
**Description**
An error is triggered when using the shares.share_permissions() function.
> NameError: name 'PermissionsList' is not defined.

**Reproduction**
Call the shares.share_permissions() function against any named share.

**Expected behavior**
The function returns a list of permissions to the share including recipient name and access level (SELECT).

**Is it a regression?**
??

**Additional context**
This is fixed by importing the PermissionsList class in sharing.py.
`from databricks.sdk.service.catalog import PermissionsList`

**Comment by Korijn** [comment]
:+1: we just ran into this as well!
