### ISSUE TITLE
'/api/2.0/secrets/get' is not in the official docs

### ISSUE THREAD

**Issue by GeorgelPreput** [databricks/databricks-sdk-py#77]
Looking through the code, I noticed you're using a call to `/api/2.0/secrets/get` to retrieve secrets remotely. That API endpoint doesn't seem to be documented in [Secrets API 2.0](https://docs.databricks.com/dev-tools/api/latest/secrets.html)

Could it please be added?

**Comment by nfx** [comment]
@GeorgelPreput , that API is to be rolled as part of DBConnect V2. It's not intended to be used directly by SDK - https://www.databricks.com/blog/2023/04/18/use-databricks-anywhere-databricks-connect-v2.html
