### ISSUE TITLE
Workspace import method name

### ISSUE THREAD

**Issue by AdeelK93** [databricks/databricks-sdk-py#91]
Hello! I'm wondering why the `import_` method has a trailing underscore, but `export` doesn't - was that intentional?

https://github.com/databricks/databricks-sdk-py/blob/c578001d0cbbaccf1f7f09715659e5d176a60f8c/databricks/sdk/service/workspace.py#L1145

**Comment by nfx** [comment]
@AdeelK93 yes, because `import` is a reserved Python keyword 🤷 what would be more logical suffix here?

**Comment by AdeelK93** [comment]
Oh! Hmm. To me the `_` implied that this was a private method in some way, which gave me pause when first trying it out.

But maybe I'm alone in that concern
